Algoritmo "alvaroquefez"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : ALVARO O MAIS BADALADO
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 01/08/2023
Var
nmr: inteiro

Inicio
escreval("Digite um número inteiro: ")
leia(nmr)
se nmr % 2 = 0 entao
escreval("O número é par")
senao
escreval("O número é ímpar" )
fimSe

Fimalgoritmo